name: docker01-exporters

x-logging: &default-logging
  driver: json-file
  options:
    max-size: "10m"
    max-file: "3"

services:
  node-exporter:
    image: quay.io/prometheus/node-exporter:v1.12.1
    restart: unless-stopped
    network_mode: host
    pid: host
    command:
      - --path.rootfs=/host
      - --web.listen-address=:9100
    volumes:
      - /:/host:ro,rslave
    logging: *default-logging

  cadvisor:
    image: ghcr.io/google/cadvisor:v0.60.5
    restart: unless-stopped
    privileged: true
    devices:
      - /dev/kmsg:/dev/kmsg
    command:
      - --docker_only=true
      - --housekeeping_interval=15s
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /srv/docker/data:/srv/docker/data:ro
      - /dev/disk:/dev/disk:ro
    ports:
      - "8080:8080"
    logging: *default-logging
